package com.ieum.domain.model

data class ChemistryInfo(
    val title: String,
    val description: String
)

object ChemistryData {
    val chemistryMap = mapOf(
        // MDEF
        Pair("MDEF", "MDEP") to ChemistryInfo("알뜰살뜰 탐험대", "가성비와 재미를 동시에 잡는, 세상에서 가장 알차게 노는 커플!"),
        Pair("MDEF", "MDEF") to ChemistryInfo("자유로운 단짝 친구", "\"어디든 좋아!\" 즉흥적인 모험을 즐기며 쿨하게 소통하는 찐사랑 사이."),
        Pair("MDEF", "MDCP") to ChemistryInfo("모험가와 안심 귀가 요정", "밖에서는 신나게 놀고, 돌아와서는 익숙한 편안함에 안기는 밸런스 굿!"),
        Pair("MDEF", "MDCF") to ChemistryInfo("말랑말랑 산책 메이트", "소소한 행복을 찾아서 여기저기 돌아다니는 귀여운 댕댕이 커플이에요."),
        Pair("MDEF", "MTEP") to ChemistryInfo("씩씩한 대장과 신중한 참모", "한 명은 앞장서고 한 명은 뒤를 살피니, 어떤 변화도 두렵지 않아요."),
        Pair("MDEF", "MTEF") to ChemistryInfo("감성 모험가와 여행 작가", "새로운 세상을 보고 느낀 감정을 소중하게 공유하는 다정한 여행자들."),
        Pair("MDEF", "MTCP") to ChemistryInfo("자유 속의 따뜻한 쉼터", "\"너랑 있으면 편안해.\" 즉흥적인 재미와 평온한 휴식이 함께해요."),
        Pair("MDEF", "MTCF") to ChemistryInfo("느릿느릿 힐링 탐험대", "서두르지 않고 우리만의 속도로 세상을 구경하는 마음 예쁜 커플."),
        Pair("MDEF", "IDEP") to ChemistryInfo("쿨한 대장과 럭셔리 게스트", "가성비 장인과 낭만 지출가가 만나 뜻밖의 시너지를 내는 꿀조합!"),
        Pair("MDEF", "IDEF") to ChemistryInfo("인생은 즐거운 축제", "오늘만 사는 것처럼 신나게 놀고, 솔직하게 감정을 표현하는 뜨거운 사이."),
        Pair("MDEF", "IDCP") to ChemistryInfo("모험 끝에 만난 아지트", "밖에서는 신나게 놀고, 안에서는 럭셔리하게 쉬는 완벽한 데이트 루틴!"),
        Pair("MDEF", "IDCF") to ChemistryInfo("감성 충만 길거리 로맨스", "발길 닿는 곳마다 특별한 추억으로 만드는, 센스 넘치는 커플이에요."),
        Pair("MDEF", "ITEP") to ChemistryInfo("유연한 리더와 사색가", "서로의 속도를 존중하며, 새로운 경험을 통해 함께 성장하는 멋진 사이."),
        Pair("MDEF", "ITEF") to ChemistryInfo("몽글몽글 감성 대장들", "\"이 느낌 너무 좋다!\" 사소한 것에서도 행복을 발견하는 예쁜 마음들."),
        Pair("MDEF", "ITCP") to ChemistryInfo("든든한 기둥과 자유로운 꽃", "흔들리지 않는 나무처럼 지켜주는 이와 그 옆에서 피어나는 꽃 같은 조화."),
        Pair("MDEF", "ITCF") to ChemistryInfo("다정한 낭만 힐러들", "서로의 존재 자체가 위로가 되는, 가장 편안하고 따뜻한 안식처예요."),

        // MDCP
        Pair("MDCP", "MDEP") to ChemistryInfo("철통 보안 사랑의 성", "철저한 계획과 익숙한 평화 속에서 가장 큰 행복을 느끼는 커플!"),
        Pair("MDCP", "MDEF") to ChemistryInfo("든든한 베이스캠프", "한 명은 밖에서 재미를 찾아오고, 한 명은 집을 따뜻하게 지키는 조화."),
        Pair("MDCP", "MDCP") to ChemistryInfo("평온한 일상 지킴이", "\"늘 먹던 걸로!\" 우리만의 루틴이 세상에서 제일 소중한 단단한 사이."),
        Pair("MDCP", "MDCF") to ChemistryInfo("포근포근 홈 데이트 장인", "익숙한 곳에서 맛있는 걸 먹으며 도란도란 이야기 나누는 게 최고예요."),
        Pair("MDCP", "MTEP") to ChemistryInfo("신뢰의 파트너십", "서로의 선을 존중하며, 계획한 미래를 향해 차근차근 나아가는 팀."),
        Pair("MDCP", "MTEF") to ChemistryInfo("고요한 호수 위의 작은 배", "잔잔한 일상 속에서 깊은 대화로 서로를 이해하는 성숙한 관계예요."),
        Pair("MDCP", "MTCP") to ChemistryInfo("흔들림 없는 평화", "갈등조차 신중하고 차분하게 해결하는, 보고 있으면 마음 편한 조합."),
        Pair("MDCP", "MTCF") to ChemistryInfo("따뜻한 차 한 잔 같은 사이", "자극적이지 않아도 은은한 향기가 오래 남는 다정한 연애를 해요."),
        Pair("MDCP", "IDEP") to ChemistryInfo("계획적인 로맨티스트", "익숙한 일상에 화려한 이벤트를 더해 서로를 감동시키는 사랑꾼들!"),
        Pair("MDCP", "IDEF") to ChemistryInfo("일상에 찾아온 무지개", "조용한 일상에 기분 좋은 에너지를 불어넣어 주는 고마운 관계예요."),
        Pair("MDCP", "IDCP") to ChemistryInfo("최고급 휴식을 즐기는 법", "\"우리 집이 최고야!\" 편안한 공간을 위해 아낌없이 투자하는 커플."),
        Pair("MDCP", "IDCF") to ChemistryInfo("낭만적인 집콕 커플", "익숙한 공간도 촛불 하나로 분위기를 바꾸는, 감각적인 사랑을 해요."),
        Pair("MDCP", "ITEP") to ChemistryInfo("신중한 설계와 조용한 지지", "보이지 않는 곳에서도 서로를 믿고 지탱해주는 아주 깊은 신뢰."),
        Pair("MDCP", "ITEF") to ChemistryInfo("차분한 일상의 감성 한 스푼", "일상의 소중함을 알면서도 새로운 감각에 눈을 뜨게 해주는 사이."),
        Pair("MDCP", "ITCP") to ChemistryInfo("영원히 변치 않을 약속", "가장 안정적인 두 사람이 만나 결코 깨지지 않는 단단한 사랑을 약속해요."),
        Pair("MDCP", "ITCF") to ChemistryInfo("포근한 이불 속 같은 사랑", "세상의 풍파로부터 서로를 지켜주는, 가장 안전한 안식처가 되어줘요."),

        // MDCF
        Pair("MDCF", "MDEP") to ChemistryInfo("힐링 요정과 가이드", "딱딱할 수 있는 계획에 부드러운 여유 한 방울을 섞어주는 다정한 관계."),
        Pair("MDCF", "MDEF") to ChemistryInfo("동네 한 바퀴 짝꿍", "소소한 행복을 찾아서 여기저기 돌아다니는 귀여운 댕댕이 커플!"),
        Pair("MDCF", "MDCP") to ChemistryInfo("포근한 집순이와 집돌이", "익숙한 곳에서 맛있는 걸 먹으며 도란도란 이야기 나누는 게 즐거워요."),
        Pair("MDCF", "MDCF") to ChemistryInfo("말랑말랑 솜사탕들", "욕심 없이 소박한 일상을 즐기며, 존재만으로도 완벽한 힐링을 느껴요."),
        Pair("MDCF", "MTEP") to ChemistryInfo("꿈을 심는 정원사들", "한 명은 길을 닦고 한 명은 꽃을 심는, 예쁜 정원 같은 커플이에요."),
        Pair("MDCF", "MTEF") to ChemistryInfo("느릿느릿 감성 여행가", "발길 닿는 대로 걷고, 마음 닿는 대로 대화하는 편안한 낭만파들."),
        Pair("MDCF", "MTCP") to ChemistryInfo("세상에서 가장 안전한 둥지", "변수 없는 일상과 깊은 배려가 만나, 마음의 안정이 파도처럼 밀려와요."),
        Pair("MDCF", "MTCF") to ChemistryInfo("은은한 달빛 같은 사이", "자극적이지 않아도 깊은 맛이 나는, 오래 보아도 질리지 않는 사랑."),
        Pair("MDCF", "IDEP") to ChemistryInfo("럭셔리 휴가와 소박한 휴식", "특별한 날의 화려함과 평범한 날의 소중함을 모두 아는 밸런스 조합!"),
        Pair("MDCF", "IDEF") to ChemistryInfo("호수에 던져진 꽃잎", "잔잔한 일상에 기분 좋은 자극을 주는, 서로에게 웃음을 주는 관계."),
        Pair("MDCF", "IDCP") to ChemistryInfo("최고급 홈캉스 메이트", "편안한 우리 집을 세상에서 가장 안락하게 꾸며 즐기는 커플이에요."),
        Pair("MDCF", "IDCF") to ChemistryInfo("꿀 떨어지는 낭만 힐러", "기분 좋은 사치와 따뜻한 배려가 넘쳐나서 늘 달달함이 한도 초과!"),
        Pair("MDCF", "ITEP") to ChemistryInfo("예술가와 따뜻한 관객", "서로의 꿈을 응원하며 조용히 지지해주는, 아주 깊고 넓은 사랑."),
        Pair("MDCF", "ITEF") to ChemistryInfo("몽글몽글 감성 수집가", "사소한 풍경도 놓치지 않고 함께 감상하는, 결이 고운 커플이에요."),
        Pair("MDCF", "ITCP") to ChemistryInfo("단단한 뿌리와 포근한 잎새", "흔들리지 않는 신뢰 위에서 마음껏 편안함을 누리는 성숙한 사이."),
        Pair("MDCF", "ITCF") to ChemistryInfo("구름 위를 걷는 평화", "걱정 고민 다 잊게 해주는, 세상에서 가장 다정한 안식처가 돼요."),

        // MTEP
        Pair("MTEP", "MDEP") to ChemistryInfo("전략적인 두뇌 팀", "함께 미래를 설계하고 도전하는 모습이 멋진, 서로를 리스펙하는 커플!"),
        Pair("MTEP", "MDEF") to ChemistryInfo("신중 가이드와 씩씩 대장", "꼼꼼한 준비에 실행력이 더해져, 어디를 가든 든든한 모험이 돼요."),
        Pair("MTEP", "MDCP") to ChemistryInfo("신뢰의 파트너십", "서로의 선을 존중하며, 계획한 미래를 향해 차근차근 나아가는 팀."),
        Pair("MTEP", "MDCF") to ChemistryInfo("설계자와 다정한 응원군", "한 명은 앞을 내다보고 한 명은 곁을 지키는, 조화로운 성장의 아이콘!"),
        Pair("MTEP", "MTEP") to ChemistryInfo("완벽주의 로맨스 서사", "같은 속도와 깊이로 서로를 이해하며, 정교한 사랑을 쌓아가는 사이."),
        Pair("MTEP", "MTEF") to ChemistryInfo("섬세 탐험가와 유연 여행가", "준비는 철저하게, 즐거움은 여유롭게! 완급 조절이 완벽한 데이트."),
        Pair("MTEP", "MTCP") to ChemistryInfo("고요하고 단단한 신뢰", "말하지 않아도 마음이 통하는, 세상에서 가장 깊은 뿌리를 내린 커플."),
        Pair("MTEP", "MTCF") to ChemistryInfo("사색하는 숲속의 연인", "조용한 대화 속에서 진심을 발견하며, 서로의 영혼을 채워주는 사이."),
        Pair("MTEP", "IDEP") to ChemistryInfo("럭셔리한 꿈의 프로젝트", "최고의 가치를 위해 함께 투자하고 노력하는, 야망 있고 로맨틱한 조합!"),
        Pair("MTEP", "IDEF") to ChemistryInfo("철저한 기획과 뜨거운 열정", "한 명은 밑그림을 그리고 한 명은 색을 칠하는 예술 작품 같은 커플."),
        Pair("MTEP", "IDCP") to ChemistryInfo("정성 가득 프리미엄 일상", "우리만의 가치를 높이기 위해 투자하며, 품격 있는 사랑을 지향해요."),
        Pair("MTEP", "IDCF") to ChemistryInfo("신중 기획과 낭만 한 방", "빈틈없는 일상에 가끔 터지는 화려한 이벤트로 매일이 설레는 관계!"),
        Pair("MTEP", "ITEP") to ChemistryInfo("영혼의 설계자들", "더 나은 우리를 위해 아낌없이 고민하고 투자하며, 깊게 소통해요."),
        Pair("MTEP", "ITEF") to ChemistryInfo("섬세 사색과 감각적 모험", "깊은 생각 끝에 만나는 새로운 자극이 즐거운, 지적인 낭만파 커플!"),
        Pair("MTEP", "ITCP") to ChemistryInfo("흔들림 없는 인생 동반자", "어떤 비바람이 불어도 서로를 믿고 지탱해줄 준비가 된 든든한 사이."),
        Pair("MTEP", "ITCF") to ChemistryInfo("지혜로운 멘토와 힐러", "서로를 성장시키고 치유해주는, 관계의 정석을 보여주는 예쁜 만남."),

        // MTEF
        Pair("MTEF", "MDEP") to ChemistryInfo("감성 여행자와 스마트 리더", "\"너만 믿고 따라갈게!\" 든든한 리드와 자유로운 감성이 만난 조합."),
        Pair("MTEF", "MDEF") to ChemistryInfo("마음이 통하는 여행가들", "새로운 세상을 보고 느낀 감정을 소중하게 공유하는 다정한 모험가들."),
        Pair("MTEF", "MDCP") to ChemistryInfo("정적인 호수 위의 작은 배", "잔잔한 일상 속에서 깊은 대화로 서로를 이해하는 성숙한 관계예요."),
        Pair("MTEF", "MDCF") to ChemistryInfo("발길 닿는 대로의 미학", "계획에 얽매이지 않고 지금 이 순간의 아름다움을 함께 만끽해요."),
        Pair("MTEF", "MTEP") to ChemistryInfo("여유로운 모험과 신중 준비", "\"이거 어때?\" 제안하고 \"좋아!\" 하며 나아가는 완벽한 페이스메이커."),
        Pair("MTEF", "MTEF") to ChemistryInfo("자유로운 두 마리 나비", "억압받지 않고 자유롭게 날아다니며, 서로의 날갯짓에 맞춰 춤춰요."),
        Pair("MTEF", "MTCP") to ChemistryInfo("안락한 의자와 창밖 풍경", "편안한 안식처에서 새로운 세상을 구경하는 듯한 평화로운 케미."),
        Pair("MTEF", "MTCF") to ChemistryInfo("은은한 가을 햇살 같은 사이", "서두르지 않아도 충분히 따뜻한, 서로의 존재로 마음이 꽉 차요."),
        Pair("MTEF", "IDEP") to ChemistryInfo("감성 충전 럭셔리 투어", "최고의 장소에서 최고의 감성을 나누는 영화 속 한 장면 같은 데이트."),
        Pair("MTEF", "IDEF") to ChemistryInfo("뜨거운 감성과 자유 영혼", "마음이 이끄는 대로 투자하고 즐기며 열정적으로 세상을 탐험해요."),
        Pair("MTEF", "IDCP") to ChemistryInfo("분위기 있는 로맨틱 데이트", "익숙한 공간도 우리만의 감성으로 특별하게 만드는 센스 만점 조합!"),
        Pair("MTEF", "IDCF") to ChemistryInfo("몽글몽글 낭만 방랑자들", "\"오늘 기분이다!\" 하며 즐거운 추억에 아낌없이 투자하는 행복한 사이."),
        Pair("MTEF", "ITEP") to ChemistryInfo("깊은 사색과 감각의 만남", "서로의 내면을 여행하듯 대화하며, 보이지 않는 가치를 함께 키워요."),
        Pair("MTEF", "ITEF") to ChemistryInfo("감수성 폭발 듀오", "\"이 느낌 너무 좋다!\" 사소한 것에도 감동하며 추억을 수집하는 마음."),
        Pair("MTEF", "ITCP") to ChemistryInfo("든든한 기둥과 자유로운 꽃", "흔들리지 않는 나무와 그 옆에서 피어나는 꽃 같은 아름다운 조화."),
        Pair("MTEF", "ITCF") to ChemistryInfo("다정한 낭만 힐러들", "서로의 마음을 누구보다 잘 읽어주는, 세상에서 가장 부드러운 사랑."),

        // MTCP
        Pair("MTCP", "MDEP") to ChemistryInfo("안정적인 미래 설계단", "변수를 최소화하고 계획된 행복을 향해 뚜벅뚜벅 걸어가는 커플."),
        Pair("MTCP", "MDEF") to ChemistryInfo("안식처와 명랑한 모험가", "밖에서 신나게 놀고 돌아온 연인을 따뜻하게 안아주는 힐링 조합."),
        Pair("MTCP", "MDCP") to ChemistryInfo("흔들림 없는 평화주의자", "우리만의 루틴과 규칙이 세상에서 가장 소중한, 단단한 뿌리의 사랑."),
        Pair("MTCP", "MDCF") to ChemistryInfo("솜사탕 같은 일상", "자극적이지 않아도 달콤하고 포근한, 일상의 소중함을 아는 사이."),
        Pair("MTCP", "MTEP") to ChemistryInfo("지혜로운 성벽과 파수꾼", "서로를 지켜준다는 믿음 아래, 아주 깊고 성숙한 대화를 나눠요."),
        Pair("MTCP", "MTEF") to ChemistryInfo("평온한 거실과 열린 창문", "안정된 관계 속에서도 가끔씩 불어오는 새로운 바람을 즐기는 커플."),
        Pair("MTCP", "MTCP") to ChemistryInfo("고요한 우주의 연인들", "세상의 소음에서 벗어나 둘만의 고요한 평화를 만끽하는 완벽한 안식."),
        Pair("MTCP", "MTCF") to ChemistryInfo("느릿느릿 따뜻한 동행", "서두를 것 하나 없이, 서로의 발걸음에 맞춰 천천히 깊어지는 사랑."),
        Pair("MTCP", "IDEP") to ChemistryInfo("안정감 위의 화려한 꽃", "든든한 신뢰를 바탕으로 가끔은 과감하게 즐기는 럭셔리한 하루!"),
        Pair("MTCP", "IDEF") to ChemistryInfo("차분한 삶에 내린 단비", "조금은 단조로울 수 있는 일상에 생동감과 열정을 더해주는 관계."),
        Pair("MTCP", "IDCP") to ChemistryInfo("프리미엄 힐링 아지트", "우리가 쉬는 공간을 최고의 가치로 가꾸며 품격 있게 사랑해요."),
        Pair("MTCP", "IDCF") to ChemistryInfo("다정한 낭만과 평온함", "따뜻한 배려와 넉넉한 마음이 만나, 싸울 일이 없는 평화로운 사이."),
        Pair("MTCP", "ITEP") to ChemistryInfo("깊은 신뢰의 건축가들", "서로의 내면을 아주 신중하게 보살피며 영원한 사랑을 지어 올려요."),
        Pair("MTCP", "ITEF") to ChemistryInfo("섬세한 감성 지킴이들", "작은 감정 하나도 놓치지 않고 소중히 다루는, 결이 고운 커플."),
        Pair("MTCP", "ITCP") to ChemistryInfo("영원한 안식처", "세상 그 어떤 곳보다 서로의 옆이 가장 편안한, 완벽한 안정감."),
        Pair("MTCP", "ITCF") to ChemistryInfo("포근한 구름 위의 대화", "부드러운 말투와 깊은 배려로 서로의 마음을 치유해주는 관계."),

        // MTCF
        Pair("MTCF", "MDEP") to ChemistryInfo("지혜로운 조력자와 리더", "한 명은 길을 닦고 한 명은 마음을 보듬는, 균형 잡힌 다정함."),
        Pair("MTCF", "MDEF") to ChemistryInfo("동네 한 바퀴 힐링 메이트", "발길 닿는 곳마다 소소한 웃음꽃이 피어나는 무해한 커플이에요."),
        Pair("MTCF", "MDCP") to ChemistryInfo("은은한 차 한 잔의 여유", "화려하지 않아도 깊은 향기가 나는, 마음 편한 연애의 정석."),
        Pair("MTCF", "MDCF") to ChemistryInfo("세상 무해한 솜사탕들", "서로에게 어떤 요구도 없이, 있는 그대로를 사랑해주는 따뜻한 사이."),
        Pair("MTCF", "MTEP") to ChemistryInfo("사색하는 숲속의 산책", "깊은 생각과 소박한 행동이 만나, 아주 평화로운 일상을 꾸려가요."),
        Pair("MTCF", "MTEF") to ChemistryInfo("잔잔한 파도와 모래사장", "밀려오고 밀려가는 감정 속에서 늘 그 자리를 지켜주는 다정한 사이."),
        Pair("MTCF", "MTCP") to ChemistryInfo("느릿느릿 다정한 그림자", "한결같은 모습으로 서로의 곁을 지키는, 가장 안정적인 동행."),
        Pair("MTCF", "MTCF") to ChemistryInfo("고요한 숲의 평화", "아무 말 하지 않아도 어색하지 않은, 영혼까지 편안한 짝꿍이에요."),
        Pair("MTCF", "IDEP") to ChemistryInfo("소박한 일상과 화려한 로망", "평범한 날도 특별하게, 특별한 날은 더 소중하게 만드는 밸런스."),
        Pair("MTCF", "IDEF") to ChemistryInfo("다정한 응원과 뜨거운 도전", "연인의 도전을 묵묵히 지지해주며 따뜻한 집이 되어주는 관계."),
        Pair("MTCF", "IDCP") to ChemistryInfo("낭만적인 홈 스윗 홈", "우리만의 공간에서 풍족하게 즐기는 소소하고도 확실한 행복!"),
        Pair("MTCF", "IDCF") to ChemistryInfo("꿀 떨어지는 힐링 캠프", "서로를 챙겨주는 마음이 너무 예뻐서 주변까지 행복해지는 커플."),
        Pair("MTCF", "ITEP") to ChemistryInfo("섬세한 마음의 정원사", "보이지 않는 마음의 상처까지 어루만져주는 깊은 사랑을 해요."),
        Pair("MTCF", "ITEF") to ChemistryInfo("몽글몽글 감성 수집가", "세상의 예쁜 것들만 골라 서로에게 보여주고 싶은 순수한 마음들."),
        Pair("MTCF", "ITCP") to ChemistryInfo("단단한 신뢰와 포근한 배려", "튼튼한 나무 아래에서 낮잠을 자는 듯한 평온한 사랑의 모습."),
        Pair("MTCF", "ITCF") to ChemistryInfo("천사들의 합창", "서로를 향한 배려가 한도 초과! 세상에서 가장 부드러운 커플."),

        // IDEP
        Pair("IDEP", "MDEP") to ChemistryInfo("최고급 전략 파트너", "꼼꼼한 계획과 확실한 투자로 매번 역대급 데이트를 만들어내는 완벽한 팀!"),
        Pair("IDEP", "MDEF") to ChemistryInfo("럭셔리 리더와 쿨한 대장", "가성비와 플렉스를 넘나들며, 솔직하게 소통하고 신나게 노는 에너지 커플."),
        Pair("IDEP", "MDCP") to ChemistryInfo("완벽한 로맨틱 가이드", "한 명은 안정감을 주고 한 명은 특별함을 더하는, 신뢰 가득한 사랑꾼들."),
        Pair("IDEP", "MDCF") to ChemistryInfo("화려한 축제와 소박한 휴식", "밖에서는 화끈하게 즐기고 안에서는 따뜻하게 쉬는, 완벽한 온오프 밸런스."),
        Pair("IDEP", "MTEP") to ChemistryInfo("로망 실현 프로젝트", "우리가 꿈꾸는 모든 것을 현실로 만드는, 가장 야심 차고 든든한 동반자."),
        Pair("IDEP", "MTEF") to ChemistryInfo("감성 충만한 럭셔리 투어", "최고의 장소에서 최고의 감성을 나누며, 서로를 깊이 배려하는 낭만파 커플."),
        Pair("IDEP", "MTCP") to ChemistryInfo("든든한 성벽 위의 불꽃놀이", "안정적인 믿음 위에서 화려한 사랑을 피워내는, 아주 단단하고 예쁜 사이."),
        Pair("IDEP", "MTCF") to ChemistryInfo("듬직한 기둥과 화려한 꽃", "묵묵한 지지와 열정적인 사랑이 만나, 서로의 존재를 빛내주는 관계예요."),
        Pair("IDEP", "IDEP") to ChemistryInfo("눈부신 다이아몬드 커플", "같은 가치관으로 아낌없이 사랑하고 투자하는, 세상에서 가장 화려한 콤비."),
        Pair("IDEP", "IDEF") to ChemistryInfo("뜨거운 심장의 모험가들", "멈추지 않는 열정과 아낌없는 표현으로 매일매일을 영화처럼 살아가는 사이."),
        Pair("IDEP", "IDCP") to ChemistryInfo("프리미엄 로맨틱 라이프", "우리만의 공간과 시간을 최고로 가꾸며, 명확한 사랑을 확인하는 커플."),
        Pair("IDEP", "IDCF") to ChemistryInfo("낭만 과부하 사랑꾼들", "하고 싶은 것도, 사고 싶은 것도 다 하며 사랑을 속삭이는 달콤한 관계."),
        Pair("IDEP", "ITEP") to ChemistryInfo("섬세한 꿈의 건축가들", "로망을 현실로 바꾸는 정성과 아낌없는 마음이 만나 깊게 소통해요."),
        Pair("IDEP", "ITEF") to ChemistryInfo("화려한 모험과 깊은 감성", "새로운 도전에 열정을 쏟으면서도 서로의 속마음을 섬세하게 살피는 사이."),
        Pair("IDEP", "ITCP") to ChemistryInfo("단단한 신뢰와 뜨거운 심장", "어떤 상황에서도 서로를 믿으며, 최고의 사랑을 위해 정성을 다해요."),
        Pair("IDEP", "ITCF") to ChemistryInfo("다정한 요정과 열정 가이드", "부드러운 배려 속에 화끈한 이벤트를 더해 매 순간이 감동인 커플."),

        // IDEF
        Pair("IDEF", "MDEP") to ChemistryInfo("에너자이저와 기획 대장", "지치지 않는 열정과 완벽한 리드가 만나 어디서든 주인공이 되는 커플!"),
        Pair("IDEF", "MDEF") to ChemistryInfo("자유로운 축제 영혼들", "\"오늘 완전 즐겁게 놀자!\" 즉흥적인 모험과 솔직한 대화가 끊이지 않아요."),
        Pair("IDEF", "MDCP") to ChemistryInfo("불꽃같은 열정과 안식처", "밖에서 신나게 에너지를 발산하고 돌아와 편안하게 쉴 수 있는 꿀조합."),
        Pair("IDEF", "MDCF") to ChemistryInfo("명랑 모험가와 힐링 요정", "잔잔한 일상에 기분 좋은 자극을 주며, 서로를 웃게 만드는 비타민 커플."),
        Pair("IDEF", "MTEP") to ChemistryInfo("뜨거운 도전과 신중한 준비", "한 명은 실행하고 한 명은 보완하니, 어떤 꿈도 다 이룰 수 있어요."),
        Pair("IDEF", "MTEF") to ChemistryInfo("감성 폭발 모험가들", "마음이 이끄는 대로 떠나고, 그곳에서 느낀 감정을 소중히 나누는 사이."),
        Pair("IDEF", "MTCP") to ChemistryInfo("활기찬 바람과 든든한 나무", "흔들림 없는 나무처럼 지켜주는 이와 그 옆에서 춤추는 바람 같은 조화."),
        Pair("IDEF", "MTCF") to ChemistryInfo("다정한 응원군과 열정맨", "하고 싶은 건 다 해보라고 응원해주는 파트너 덕분에 늘 든든해요."),
        Pair("IDEF", "IDEP") to ChemistryInfo("열정 폭발 폭주기관차", "\"우리 오늘 최고로 놀자!\" 뜨거운 열정과 완벽한 로망이 만난 무적 커플."),
        Pair("IDEF", "IDEF") to ChemistryInfo("내일이 없는 낭만파들", "지금 이 순간의 행복을 위해 모든 걸 던지는, 세상에서 가장 쿨한 사이."),
        Pair("IDEF", "IDCP") to ChemistryInfo("화끈한 즐거움과 안락한 집", "신나게 모험하고 아늑한 우리만의 공간에서 럭셔리하게 쉬는 데이트!"),
        Pair("IDEF", "IDCF") to ChemistryInfo("꿀 떨어지는 낭만 방랑자", "발길 닿는 대로 가되 감성은 듬뿍! 사랑 표현도 가장 화끈한 커플."),
        Pair("IDEF", "ITEP") to ChemistryInfo("열정과 사색의 콜라보", "넘치는 에너지를 깊이 있는 생각으로 다듬어주는, 성숙한 성장의 관계."),
        Pair("IDEF", "ITEF") to ChemistryInfo("몽글몽글 감성 대장들", "\"이 느낌 너무 좋아!\" 사소한 것에서도 행복을 터뜨리는 예쁜 마음들."),
        Pair("IDEF", "ITCP") to ChemistryInfo("든든한 버팀목과 뜨거운 꽃", "한결같은 신뢰 위에서 열정적인 사랑의 꽃을 피우는 아름다운 사이."),
        Pair("IDEF", "ITCF") to ChemistryInfo("세상 다정한 힐러와 모험가", "지친 마음은 다정하게 녹여주고, 즐거움은 배로 만드는 행복 커플."),

        // IDCP
        Pair("IDCP", "MDEP") to ChemistryInfo("최고급 사랑의 요새", "완벽한 계획 하에 우리만의 공간을 최고로 가꾸는, 품격 있는 커플."),
        Pair("IDCP", "MDEF") to ChemistryInfo("안락한 둥지와 모험가", "\"밖에서 재밌었어? 이제 쉬자!\" 편안함과 즐거움이 공존하는 사이."),
        Pair("IDCP", "MDCP") to ChemistryInfo("프리미엄 일상의 수호자", "\"우리 집이 제일 좋아!\" 익숙한 곳에서의 럭셔리한 행복을 아는 커플."),
        Pair("IDCP", "MDCF") to ChemistryInfo("따뜻한 로맨틱 홈캉스", "정성 가득한 공간에서 소소하지만 확실한 행복을 누리는 다정한 사이."),
        Pair("IDCP", "MTEP") to ChemistryInfo("신뢰와 품격의 파트너십", "서로의 가치를 높여주며, 안정적인 미래를 함께 그려가는 멋진 팀!"),
        Pair("IDCP", "MTEF") to ChemistryInfo("분위기 있는 사색의 공간", "조용한 일상에 감성적인 지출을 더해, 매 순간을 특별하게 만들어요."),
        Pair("IDCP", "MTCP") to ChemistryInfo("영원히 깨지지 않는 평화", "가장 안정적이고 깊은 신뢰를 바탕으로, 편안한 사랑을 약속해요."),
        Pair("IDCP", "MTCF") to ChemistryInfo("다정한 온기가 가득한 집", "서두르지 않아도 충분히 따뜻한, 서로의 존재로 마음이 꽉 차는 사이."),
        Pair("IDCP", "IDEP") to ChemistryInfo("로맨틱한 우리만의 성", "아낌없는 투자와 명확한 표현으로, 세상에서 가장 소중한 사랑을 해요."),
        Pair("IDCP", "IDEF") to ChemistryInfo("아늑한 일상과 무지개", "정적인 삶에 활기를 불어넣어 주는 연인 덕분에 매일이 새롭답니다."),
        Pair("IDCP", "IDCP") to ChemistryInfo("완벽한 소울메이트", "취향부터 생활 방식까지 똑 닮아, 함께 있는 게 세상에서 제일 편해요."),
        Pair("IDCP", "IDCF") to ChemistryInfo("달콤한 낭만 가득한 우리집", "기분 좋은 플렉스와 다정한 대화가 넘쳐나는, 꿀 떨어지는 커플."),
        Pair("IDCP", "ITEP") to ChemistryInfo("섬세한 설계와 조용한 지지", "보이지 않는 곳에서도 서로를 믿고 지탱해주는 아주 깊은 신뢰."),
        Pair("IDCP", "ITEF") to ChemistryInfo("차분한 일상의 감성 한 스푼", "일상의 소중함을 알면서도 새로운 감각에 눈을 뜨게 해주는 사이."),
        Pair("IDCP", "ITCP") to ChemistryInfo("영원히 변치 않을 약속", "어떤 비바람이 불어도 우리만의 공간과 사랑은 끝까지 지켜내요."),
        Pair("IDCP", "ITCF") to ChemistryInfo("포근한 이불 속 같은 사랑", "세상의 소음으로부터 서로를 지켜주는, 가장 안전한 안식처가 돼요."),

        // IDCF
        Pair("IDCF", "MDEP") to ChemistryInfo("낭만 부자와 스마트 가이드", "계획적인 데이트 속에 낭만적인 지출이 더해져 만족도 200%인 관계."),
        Pair("IDCF", "MDEF") to ChemistryInfo("감성 충만한 길거리 로맨스", "발길 닿는 곳마다 특별한 추억으로 만드는, 센스 넘치는 커플이에요."),
        Pair("IDCF", "MDCP") to ChemistryInfo("낭만적인 집콕 커플", "익숙한 공간도 작은 소품 하나로 분위기를 바꾸는, 감각적인 사랑."),
        Pair("IDCF", "MDCF") to ChemistryInfo("무해하고 달콤한 솜사탕", "서로를 챙겨주는 예쁜 마음과 넉넉한 배려가 넘쳐나는 힐링 조합."),
        Pair("IDCF", "MTEP") to ChemistryInfo("신중한 계획과 낭만 한 방", "빈틈없는 일상에 가끔 터지는 화려한 이벤트로 매일이 설레는 관계."),
        Pair("IDCF", "MTEF") to ChemistryInfo("몽글몽글 낭만 방랑자들", "\"오늘 기분이다!\" 하며 즐거운 추억에 아낌없이 투자하는 행복 커플."),
        Pair("IDCF", "MTCP") to ChemistryInfo("다정한 낭만과 평온함", "따뜻한 배려와 넉넉한 마음이 만나, 싸울 일이 없는 평화로운 사이."),
        Pair("IDCF", "MTCF") to ChemistryInfo("꿀 떨어지는 힐링 캠프", "서로를 챙겨주는 마음이 너무 예뻐서 주변까지 행복해지는 사이예요."),
        Pair("IDCF", "IDEP") to ChemistryInfo("낭만 과부하 사랑꾼들", "하고 싶은 것도 다 하고 표현도 듬뿍 하는, 세상에서 가장 달달한 팀."),
        Pair("IDCF", "IDEF") to ChemistryInfo("즉흥 낭만과 뜨거운 열정", "기분 내키는 대로 떠나고 마음껏 사랑하는, 영화 속 주인공 커플."),
        Pair("IDCF", "IDCP") to ChemistryInfo("달콤한 낭만 가득한 우리집", "편안한 장소에서 풍족하게 즐기는, 웃음소리가 끊이지 않는 연애."),
        Pair("IDCF", "IDCF") to ChemistryInfo("천사들의 로맨틱 축제", "서로를 위해 아낌없이 주고 배려하는, 세상에서 가장 부드러운 사랑."),

        // ITEP
        Pair("ITEP", "MDEP") to ChemistryInfo("완벽한 로망 설계단", "철저한 계획과 깊은 사색이 만나, 우리가 꿈꾸는 미래를 현실로 지어 올려요."),
        Pair("ITEP", "MDEF") to ChemistryInfo("신중한 가이드와 모험가", "새로운 도전 속에서도 서로의 마음을 세심하게 살피는, 아주 성숙한 조합."),
        Pair("ITEP", "MDCP") to ChemistryInfo("깊은 신뢰의 수호자들", "보이지 않는 곳에서도 서로를 믿고 지탱해주는, 뿌리 깊은 사랑을 해요."),
        Pair("ITEP", "MDCF") to ChemistryInfo("예술가와 따뜻한 관객", "서로의 꿈을 조용히 응원하며 지지해주는, 아주 깊고 넓은 바다 같은 사랑."),
        Pair("ITEP", "MTEP") to ChemistryInfo("영혼의 설계자들", "더 나은 우리를 위해 함께 고민하고 투자하며, 지적인 낭만을 즐기는 사이."),
        Pair("ITEP", "MTEF") to ChemistryInfo("사색과 감각의 만남", "깊은 대화 끝에 만나는 새로운 자극이 즐거운, 품격 있는 낭만파 커플!"),
        Pair("ITEP", "MTCP") to ChemistryInfo("흔들림 없는 신뢰의 성", "어떤 비바람이 불어도 서로를 믿고 지탱해줄 준비가 된 든든한 사이."),
        Pair("ITEP", "MTCF") to ChemistryInfo("마음의 정원사들", "보이지 않는 마음의 상처까지 어루만져주는, 세상에서 가장 다정한 관계."),
        Pair("ITEP", "IDEP") to ChemistryInfo("화려한 꿈의 실현", "아낌없는 마음과 정교한 계획이 만나, 매번 역대급 로맨스를 기록해요."),
        Pair("ITEP", "IDEF") to ChemistryInfo("깊은 생각과 뜨거운 열정", "넘치는 에너지를 따뜻하게 감싸 안아주는, 서로의 세계를 넓혀주는 만남."),
        Pair("ITEP", "IDCP") to ChemistryInfo("정성 가득 프리미엄 일상", "우리만의 가치를 높이기 위해 투자하며, 우아하고 다정한 사랑을 지향해요."),
        Pair("ITEP", "IDCF") to ChemistryInfo("섬세한 감각과 낭만 한 방", "사소한 감정 하나도 놓치지 않고 챙겨주는, 결이 고운 커플이에요."),
        Pair("ITEP", "ITEP") to ChemistryInfo("완벽한 감성 소울메이트", "말하지 않아도 서로의 깊은 속마음을 꿰뚫어 보는, 영혼의 동반자예요."),
        Pair("ITEP", "ITEF") to ChemistryInfo("몽글몽글 낭만 건축가들", "새로운 곳을 향한 설렘과 서로를 향한 배려가 완벽하게 어우러지는 사이."),
        Pair("ITEP", "ITCP") to ChemistryInfo("단단한 약속과 깊은 애정", "어떤 상황에서도 흔들리지 않는 사랑을 약속하며, 차근차근 미래를 쌓아요."),
        Pair("ITEP", "ITCF") to ChemistryInfo("지혜로운 멘토와 다정한 힐러", "서로를 치유하고 성장시키는 모습이 너무 예쁜, 관계의 정석 커플!"),

        // ITEF
        Pair("ITEF", "MDEP") to ChemistryInfo("든든 리더와 감성 여행자", "\"너만 믿고 따라갈게!\" 든든한 리드와 자유로운 감성이 만난 예쁜 관계."),
        Pair("ITEF", "MDEF") to ChemistryInfo("몽글몽글 감성 모험가들", "\"이 느낌 너무 좋다!\" 사소한 것에서도 행복을 발견하는 예쁜 마음들."),
        Pair("ITEF", "MDCP") to ChemistryInfo("차분한 일상의 감성 한 스푼", "일상의 소중함을 알면서도 새로운 감각에 눈을 뜨게 해주는 고마운 사이."),
        Pair("ITEF", "MDCF") to ChemistryInfo("몽글몽글 감성 수집가들", "사소한 풍경도 놓치지 않고 함께 감상하는, 결이 고운 커플이에요."),
        Pair("ITEF", "MTEP") to ChemistryInfo("섬세 사색과 감각적 모험", "깊은 생각 끝에 만나는 새로운 자극이 즐거운, 지적인 낭만파 커플!"),
        Pair("ITEF", "MTEF") to ChemistryInfo("감수성 폭발 듀오", "\"이 느낌 너무 좋다!\" 사소한 것에도 감동하며 추억을 수집하는 마음들."),
        Pair("ITEF", "MTCP") to ChemistryInfo("섬세한 감성 지킴이들", "작은 감정 하나도 놓치지 않고 소중히 다루는, 다정함이 넘치는 사이."),
        Pair("ITEF", "MTCF") to ChemistryInfo("세상 예쁜 것들 수집단", "주변의 예쁜 것들만 골라 서로에게 보여주고 싶은 순수한 마음들."),
        Pair("ITEF", "IDEP") to ChemistryInfo("화려한 모험과 깊은 감성", "새로운 도전에 열정을 쏟으면서도 서로의 속마음을 섬세하게 살피는 사이."),
        Pair("ITEF", "IDEF") to ChemistryInfo("열정적 모험과 자유 영혼", "마음이 이끄는 대로 투자하고 즐기며, 뜨겁게 세상을 탐험하는 커플."),
        Pair("ITEF", "IDCP") to ChemistryInfo("감각적인 로맨틱 데이트", "익숙한 공간도 우리만의 감성으로 특별하게 만드는 센스 만점 조합!"),
        Pair("ITEF", "IDCF") to ChemistryInfo("감수성 폭발 낭만 듀오", "세상의 예쁜 것들만 골라 서로에게 보여주고 싶은 순수한 마음들."),
        Pair("ITEF", "ITEP") to ChemistryInfo("섬세한 감성과 깊은 생각", "서로의 내면을 여행하듯 대화하며, 보이지 않는 가치를 함께 키워가요."),
        Pair("ITEF", "ITEF") to ChemistryInfo("자유로운 두 마리 나비", "억압받지 않고 자유롭게 날아다니며 서로의 날갯짓에 맞춰 춤춰요."),
        Pair("ITEF", "ITCP") to ChemistryInfo("든든한 기둥과 자유로운 꽃", "흔들리지 않는 나무처럼 지켜주는 이와 그 옆에서 피어나는 꽃 같은 조화."),
        Pair("ITEF", "ITCF") to ChemistryInfo("다정한 낭만 힐러들", "서로의 마음을 누구보다 잘 읽어주는, 세상에서 가장 부드러운 사랑."),

        // ITCP
        Pair("ITCP", "MDEP") to ChemistryInfo("완벽한 신뢰의 동반자", "서로의 가치관을 존중하며, 보이지 않는 곳에서도 서로를 지탱해줘요."),
        Pair("ITCP", "MDEF") to ChemistryInfo("든든한 기둥과 자유로운 꽃", "흔들리지 않는 나무처럼 지켜주는 이와 그 옆에서 피어나는 꽃 같은 조화."),
        Pair("ITCP", "MDCP") to ChemistryInfo("영원히 변치 않을 약속", "가장 안정적인 두 사람이 만나 결코 깨지지 않는 단단한 사랑을 약속해요."),
        Pair("ITCP", "MDCF") to ChemistryInfo("단단한 뿌리와 포근한 잎새", "흔들리지 않는 신뢰 위에서 마음껏 편안함을 누리는 성숙한 사이."),
        Pair("ITCP", "MTEP") to ChemistryInfo("흔들림 없는 인생의 동반자", "어떤 비바람이 불어도 서로를 믿고 지탱해줄 준비가 된 든든한 사이."),
        Pair("ITCP", "MTEF") to ChemistryInfo("든든한 버팀목과 자유로운 꽃", "흔들리지 않는 나무처럼 지켜주는 이와 그 옆에서 피어나는 꽃 같은 조화."),
        Pair("ITCP", "MTCP") to ChemistryInfo("영원한 안식처", "세상 그 어떤 곳보다 서로의 옆이 가장 편안한, 완벽한 안정감."),
        Pair("ITCP", "MTCF") to ChemistryInfo("단단한 신뢰와 포근한 배려", "튼튼한 나무 아래에서 낮잠을 자는 듯한 평온한 사랑의 모습."),
        Pair("ITCP", "IDEP") to ChemistryInfo("단단한 신뢰와 뜨거운 심장", "어떤 상황에서도 서로를 믿으며, 최고의 사랑을 위해 정성을 다해요."),
        Pair("ITCP", "IDEF") to ChemistryInfo("든든한 버팀목과 뜨거운 꽃", "한결같은 신뢰 위에서 열정적인 사랑의 꽃을 피우는 아름다운 사이."),
        Pair("ITCP", "IDCP") to ChemistryInfo("영원히 변치 않을 약속", "어떤 비바람이 불어도 우리만의 공간과 사랑은 끝까지 지켜내요."),
        Pair("ITCP", "IDCF") to ChemistryInfo("단단한 신뢰와 넉넉한 사랑", "튼튼한 나무 아래에서 단잠을 자는 듯한, 평온하고 풍요로운 사랑."),
        Pair("ITCP", "ITEP") to ChemistryInfo("깊은 신뢰의 건축가들", "서로의 내면을 아주 신중하게 보살피며 영원한 사랑을 지어 올려요."),
        Pair("ITCP", "ITEF") to ChemistryInfo("든든한 버팀목과 자유로운 꽃", "흔들리지 않는 나무처럼 지켜주는 이와 그 옆에서 피어나는 꽃 같은 조화."),
        Pair("ITCP", "ITCP") to ChemistryInfo("세상에서 가장 단단한 우리", "아무도 깰 수 없는 무적의 믿음을 바탕으로 사랑하는 완벽한 짝꿍."),
        Pair("ITCP", "ITCF") to ChemistryInfo("포근한 구름 위의 대화", "부드러운 말투와 깊은 배려로 서로의 마음을 치유해주는 성숙한 관계."),

        // ITCF
        Pair("ITCF", "MDEP") to ChemistryInfo("가이드와 솜사탕 여행자", "계획적인 일상에 쉼표가 되어주는 단비 같은 파트너십을 보여줘요."),
        Pair("ITCF", "MDEF") to ChemistryInfo("다정한 낭만 힐러들", "서로의 존재 자체가 위로가 되는, 가장 편안하고 따뜻한 안식처예요."),
        Pair("ITCF", "MDCP") to ChemistryInfo("포근한 이불 속 같은 사랑", "세상의 풍파로부터 서로를 지켜주는, 가장 안전한 안식처가 되어줘요."),
        Pair("ITCF", "MDCF") to ChemistryInfo("구름 위를 걷는 듯한 평화", "걱정 고민 다 잊게 해주는, 세상에서 가장 다정한 안식처가 되어줘요."),
        Pair("ITCF", "MTEP") to ChemistryInfo("지혜로운 멘토와 다정한 힐러", "서로를 성장시키고 치유해주는, 관계의 정석을 보여주는 예쁜 만남."),
        Pair("ITCF", "MTEF") to ChemistryInfo("다정한 낭만 힐러들", "서로의 마음을 누구보다 잘 읽어주는, 세상에서 가장 부드러운 사랑을 해요."),
        Pair("ITCF", "MTCP") to ChemistryInfo("포근한 구름 위의 대화", "부드러운 말투와 깊은 배려로 서로의 마음을 치유해주는 관계."),
        Pair("ITCF", "MTCF") to ChemistryInfo("천사들의 합창", "서로를 향한 배려가 한도 초과! 세상에서 가장 부드러운 커플."),
        Pair("ITCF", "IDEP") to ChemistryInfo("다정한 요정과 열정 가이드", "부드러운 배려 속에 화끈한 이벤트를 더해 매 순간이 감동인 커플."),
        Pair("ITCF", "IDEF") to ChemistryInfo("세상 다정한 힐러와 모험가", "지친 마음은 다정하게 녹여주고, 즐거움은 배로 만드는 행복 커플."),
        Pair("ITCF", "IDCP") to ChemistryInfo("포근한 이불 속 같은 사랑", "세상의 소음으로부터 서로를 지켜주는, 가장 안전한 안식처가 돼요."),
        Pair("ITCF", "IDCF") to ChemistryInfo("구름 위를 걷는 솜사탕들", "걱정 고민 다 잊게 해주는, 세상에서 가장 다정한 안식처가 되어줘요."),
        Pair("ITCF", "ITEP") to ChemistryInfo("지혜로운 멘토와 힐러", "서로를 성장시키고 치유해주는, 관계의 정석을 보여주는 예쁜 만남."),
        Pair("ITCF", "ITEF") to ChemistryInfo("다정한 낭만 힐러들", "서로의 마음을 누구보다 잘 읽어주는, 세상에서 가장 부드러운 사랑을 해요."),
        Pair("ITCF", "ITCP") to ChemistryInfo("포근한 구름 위의 대화", "부드러운 말투와 깊은 배려로 서로의 마음을 치유해주는 성숙한 관계."),
        Pair("ITCF", "ITCF") to ChemistryInfo("무해한 천사들의 낙원", "\"너만 있으면 다 괜찮아.\" 존재만으로도 완벽한 힐링이 되는 축복 같은 커플.")
    )

    fun getChemistry(myMbti: String, partnerMbti: String): ChemistryInfo? {
        return chemistryMap[Pair(myMbti, partnerMbti)] ?: chemistryMap[Pair(partnerMbti, myMbti)]
    }
}
